# Generated by Django 4.0.1 on 2022-01-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('ST', 'Student'), ('TE', 'Teacher'), ('SA', 'SchoolAdmin')], max_length=2, null=True),
        ),
    ]
