# Generated by Django 4.0.1 on 2022-01-17 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_remove_lecture_school_remove_lecture_schoolclass_and_more'),
        ('accounts', '0004_schooladmin_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooladmin',
            name='school',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_admin', to='schools.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_list', to='schools.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='schoolclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_list', to='schools.class'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_list', to='schools.school'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='schoolclass',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='schools.class'),
        ),
    ]
