# Generated by Django 4.0.1 on 2022-01-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_schooladmin_school_student_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='guardian_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
