# Generated by Django 4.0.1 on 2022-01-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_student_guardian_phone_number_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardian_phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
