stages:
  - build
  - deploy

build:
  stage: build
  only:
    - develop@s06-webmobile1-sub2/S06P12D209
  script:
    - docker-compose build
  tags:
    - first

deploy:
  stage: deploy
  only:
    - develop@s06-webmobile1-sub2/S06P12D209
  script:
    - docker-compose up -d
    - cp -r ~/cert ./docker/nginx/cert
  tags:
    - first
