# Generated by Django 4.0.1 on 2022-01-15 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField(max_length=1)),
                ('class_num', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lecture_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('lecture_name', models.CharField(max_length=10)),
                ('lecture_time_list', models.JSONField(max_length=10)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='schools.school')),
                ('schoolclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='schools.class')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.school'),
        ),
    ]
