# Generated by Django 4.0.1 on 2022-01-17 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0003_alter_class_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='school',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='schoolclass',
        ),
        migrations.AddField(
            model_name='lecture',
            name='user_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='lecture_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='class',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_list', to='schools.school'),
        ),
    ]
